name: Deploy to Amazon Linux

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: <13.61.21.144>  # Remplace par l'IP publique de ton instance AWS
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22  # Ajout explicite du port SSH
          script: |
            cd ~/mon-projet || mkdir ~/mon-projet && cd ~/mon-projet
            git pull origin main || git clone git@github.com:<TON_UTILISATEUR_GITHUB>/<TON_REPO>.git .
            echo "Déploiement réussi"
