name: Deploy to Debian

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: <13.61.21.144>
          username: admin  # ou "admin" selon ton instance
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connexion SSH réussie"
