name: Deploy to Debian

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: <13.61.21.144>
          username: admin  # ou "admin" selon ton instance
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connexion SSH réussie"
            
            # Vérifier si le dossier existe sinon le créer
            if [ ! -d "/home/debian/mon-projet" ]; then
              echo "Dossier ~/mon-projet absent, clonage du dépôt..."
              git clone git@github.com:<TON_UTILISATEUR_GITHUB>/<TON_REPO>.git /home/debian/mon-projet
            else
